#!/usr/bin/env python
import sys
import os
from sys import argv
a ,inppath ,answ= argv
#inppath is the path of .xyz file
#we take the path of it from user and if there is no file we send error
assert os.path.exists(inppath), "I did not find the file at, "+str(inppath)
m0='atom'
infile=open(inppath,"r")

if answ == "y":# this is for save output in a file"
	out_file =raw_input("enter a name for the outputs:")
	while os.path.exists(os.getcwd()+"/"+out_file)==True:
		be=raw_input("there is a file withname of "+ str(out_file) +" do you want remove it?(y/n)")
		if be =="y":
			os.remove(out_file)
		else:
			out_file=raw_input("enter new output name:") 
	for i,line in enumerate(infile):
		if i!=0 and i!=1:
			for m,word in enumerate(line.split()):
				if m==0:
					m4=word					
				elif m==1:
					m1=word
				elif m==2:
					m2=word
				elif m==3:
					m3=word
			print "%s   %s   %s   %s   %s" %(m0 , m1 , m2 , m3 , m4)
			with open(out_file,"a") as out :
				out.write("%s   %s   %s   %s   %s \n"  %(m0 , m1 , m2 , m3 , m4))
				out.close()

else:#just for display showing
	for i,line in enumerate(infile):
		if i!=0 and i!=1:
			for m,word in enumerate(line.split()):
				if m==0:
					m4=word					
				elif m==1:
					m1=word
				elif m==2:
					m2=word
				elif m==3:
					m3=word
			print "%s   %s   %s   %s   %s" %(m0 , m1 , m2 , m3 , m4)
			
infile.close()
